### ISSUE TITLE
Vimeo no longer works

### ISSUE THREAD

**Issue by yakky** [FlashJunior/OSFlashVideoPlayer#29]
Vimeo video loading does not work anymore; just tested in http://www.flashjunior.ch/archiv/flvplayer/2/ using one of the example vimeo url (tried with no 3rd level domain, www domain and player domain)

**Comment by FlashJunior** [comment]
hmm... http://bitcast.vimeo.com/vimeo/swf/moogaloop.swf is not working...

i'think they changed there api :-/
https://github.com/vimeo/player-api/tree/master/actionscript

**Comment by yakky** [comment]
I'm available for testing if needed

**Comment by mitar** [comment]
It should be `https://api.vimeo.com/moogaloop_api.swf` I believe.

**Comment by abrown1982** [comment]
I've managed to edit the swf to fix the URL it requests from.  Will suggest a patch, and otherwise fork.  In the mean time, you can grab the file here: http://www.fileconvoy.com/dfl.php?id=g8b6b5cb55e6885d099925789393cc7392f11d6ee2  or do it yourself, http://www.free-decompiler.com/flash/ is a great tool for tweaking and recompiling swf files.

**Comment by abrown1982** [comment]
Have forked and submitted a pull request, only did a v quick fix on that 1 bug however and its possible there are other issues caused by the recompile - https://github.com/Level-Up/OSFlashVideoPlayer

**Comment by FlashJunior** [comment]
hi @abrown1982 i updated http://www.flashjunior.ch/archiv/flvplayer/2/ with your swf (from https://github.com/Level-Up/OSFlashVideoPlayer), but the playbutton from vimeo is not working :-/

> Error #2044: error unverarbeitet. text=Error #2048: Verletzung der Sicherheits-Sandbox: https://api.vimeo.com/moogaloop_api.swf?clip_id=3740633&width=400&height=300&fullscreen=0 kann keine Daten von https://a.vimeocdn.com/p/flash/moogaloop/5.2.55/controllers/videoControllerProgressive.swf laden.

**Comment by abrown1982** [comment]
I just spent way too long looking at this :)   Debugged your site and it looks like its the copy of player.swf you have thats causing issues.  I downloaded a new copy from the update I made on github and it works, but when I use the copy on your site it does not work.  Did you get the file directly?  https://github.com/Level-Up/OSFlashVideoPlayer/raw/master/player.swf

**Comment by FlashJunior** [comment]
If i take your swf it works. but if i dowload your source files en generate the files, it's not working.
