### ISSUE TITLE
Time doesnot updates

### ISSUE THREAD

**Issue by uurrahman** [FlashJunior/OSFlashVideoPlayer#30]
I've downloaded your source code, the time does not updates neither the duration. When ever I try to tweek the code gives errors, cause its difficult figuring out what does what without proper comments...

**Comment by uurrahman** [comment]
never mind! actually the problem was that my system didn't have the font you used after changing the font family it worked! Thanks for your share...

**Comment by FlashJunior** [comment]
next time you should use https://github.com/johndyer/mediaelement :-)
